### ISSUE TITLE
Hi, where can I get the data "x_dev_text_utterances.pickle" in multimodal_baseline.ipynb? 

### ISSUE THREAD

**Issue by Yustarzzz** [ankurbhatia24/MULTIMODAL-EMOTION-RECOGNITION#2]
Hi, while I running multimodal_baseline.ipynb, I get some error like 'FileNotFoundError: [Errno 2] No such file or directory: 'X_dev_text_utterances.pickle'.

Where can I get that file?

**Comment by ankurbhatia24** [comment]
Hi! You can check it out here: [link](https://drive.google.com/drive/folders/12ASDScVn2cCmgs_XWerQVgu1A9nAViGO?usp=sharing)
