### ISSUE TITLE
#Load frame data issue 

### ISSUE THREAD

**Issue by elyorman** [ankurbhatia24/MULTIMODAL-EMOTION-RECOGNITION#3]

**Comment by ankurbhatia24** [comment]
> ![image](https://user-images.githubusercontent.com/60263344/91024713-4b57fe80-e633-11ea-90a5-0b26e1a8695b.png)
> 
> for some reason I am getting this error. Could you help me with this?

I have checked in mine, its working fine. The problem might be due to loading the large file in Colab (But I think it should work as its not as big). You might want to look for a solution here: [https://github.com/googlecolab/colabtools/issues/510](url).
